{% set name = "bdsim-g4" %}
{% set version = "1.7.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bdsim-collaboration/bdsim/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8923a197c97984e32651f877c35c3f759ca8d20b661aaec200b83dbd72e4d7d9

build:
  skip: True  # [win]
  script: ${RECIPE_DIR}/build_bdsim.sh
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}  # [linux]
    - cmake
    - make
    - bison
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]

  host:
    - clhep
    - xerces-c
    - root_base >=6.32.0
    - geant4 >=11.2.2
    - qt-main 
    - libzlib


test:
  requires:

  commands:
    - $RECIPE_DIR/test_bdsim.sh

about:
  home: http://bdsim-collaboration.github.io/web
  summary: BDSIM is a code to make 3D models of particle accelerators using Geant4.
  description: |
    Beam Delivery Simulation (BDSIM) is a C++ program that utilises the Geant4 toolkit to simulate
    both the transport of particles in an accelerator and their interaction with the accelerator
    material. BDSIM is capable of simulating a wide variety of accelerator components and magnets
    with Geant4 geometry dynamically built based on a text input file. Thick lens accelerator
    tracking routines are provided for fast accurate tracking in a vacuum.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENCE.txt
  doc_url: https://bdsim-collaboration.github.io/bdsim/sphinx/index.html
  dev_url: https://bdsim-collaboration.github.io/bdsim/sphinx/developer.html

extra:
  recipe-maintainers:
    - stewartboogert
